ProjectUnite/ProjectUnite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
	url(r'^$', 'profiles.views.home', name='home'),
    url(r'^myProjects/$', 'projects.views.my_projects', name='my_projects'),
	url(r'^contact/$', 'profiles.views.contact', name='contact'),
	url(r'^edit/$', 'profiles.views.edit_profile', name='edit_profile'),

	
    #url(r'^myProjects/newproject/$', 'projects.views.new_project', name='new_project'),
    url(r'^newproject/$', 'projects.views.new_project', name='new_project'),
    url(r'^search/$', 'profiles.views.search_profiles', name='search_profiles'),
    url(r'^projectlist/$', 'projects.views.search_projects', name='search_projects'),
    url(r'^all/$', 'profiles.views.all', name='all'),
	#url(r'^about/$', 'ProjectUnite.views.about', name='about'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^projects/(?P<projectID>\w+)/$','projects.views.single_project', name = 'single_project'),
    url(r'^editpro/(?P<projectID>\w+)/$','projects.views.edit_project', name = 'edit_project'),
    url(r'^members/(?P<userID>\w+)/$','profiles.views.single_user', name = 'single_user'),
    url(r'^accounts/', include('registration.backends.default.urls')),
] 
if settings.DEBUG:
	urlpatterns +=  static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

ProjectUnite/profiles/models.py
from django.db import models
from django.contrib.auth.models import User


CATEGORY_OPTIONS = (
	('Business and Commerce', 'Business and Commerce'),
	('Architecture, Construction, Urban Design', 'Architecture, Construction, Urban Design'),
	('Fashion & Style', 'Fashion & Style'),
	('Computer Science and Information Technology', 'Computer Science and Information Technology'),
	('Healthcare','Healthcare'),
	('Retail & Sales','Retail & Sales'),
	('Food & Restaurant', 'Food & Restaurant'),
	('Charity and fundraising organising', 'Charity and fundraising organising'),
	('Research and Theses', 'Research and Theses'),
	)

LOCATION_OPTIONS = (
	('Melbourne', 'Melbourne'),
	('Brunswick', 'Brunswick'),
	('WorldWide', 'WorldWide'),
)

class SignUp(models.Model):
	#user = models.ForeignKey(SignUp)
	email = models.EmailField()
	user = models.ForeignKey(User)
	userID = models.AutoField(primary_key=True)
	full_name = models.CharField(max_length=40)
	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
	updated = models.DateTimeField(auto_now_add=False, null = True, blank = True)
	expertise = models.CharField(max_length = 50, choices = CATEGORY_OPTIONS)
	location = models.CharField(max_length=50, choices = LOCATION_OPTIONS)
		#might need text widget
	skills = models.TextField()
		#Qualifications = models.TextField()
	Experience = models.TextField()
	CurrentDegree = models.CharField(max_length=40, blank = True, null = True)
	Currentprojects = models.TextField()
	
	active = models.BooleanField(default = True)
	#picture = models.ImageField(upload_to=upload_location, null)
	picture = models.ImageField(upload_to="images/", null = True, blank = True)	
	def __unicode__(self):
		return self.full_name
# Create your models here.

#class SearchProfiles(models.Model):

#class UserPicture(models.Model):
#	user = models.ForeignKey(User)
#	timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
#	active = models.BooleanField(default = True)
#	thumbnail = models.BooleanField(default = False)
#	def __unicode__(self):
#		return str(self.image)

ProjectUnite/templates/all.html
  {% extends "base.html" %}
  {% block content %}
  {% for user in users %}
 <table border = "1" style = "width:100%">
 	<tr>
 		<td><li><a href = '/members/{{ user.username }}'>{{ user }}</td></a> {% for item in user.signup_set.all %}<td>Email : {{ item }}</td> <td>Location : {{ item.location }}</td></br>
 	<td>{{ item.skills }}</td>{% endfor %}</li>
 </tr></br>
 </table>
  {% endfor %}
  {% endblock %}

ProjectUnite/templates/allproject.html
  {% extends "base.html" %}
  {% block content %}
  <h1> Search results for Projects </h1>


 {% for project in projects %}
  <li><a href = '/projects/{{ project.projectID }}'>{{ project }}</a> {% for item in project.ProjectTitle_set.all %}{{ item }}{% endfor %}</li>
  {% endfor %}

  <h4>Testing</h4>
  {% endblock %}

ProjectUnite/templates/editProject.html
 {% extends "base.html" %}
 {% load crispy_forms_tags %}
   {% block content %}
 <h1> Create/Edit a new project</h1>
 	<h1>{{ title }}</h1>
<form method='POST' action = '.'>{% csrf_token %}
	{{ form|crispy }}
	
<input class = 'btn btn-primary' type='submit' value = 'SUBMIT'/>


</form>


  {% endblock %}

ProjectUnite/templates/error.html
{% extends "base.html" %}
{% block content %}
{{ title }}
{% endblock %}

ProjectUnite/templates/forms.html
<form method='POST' action = '.'>{% csrf_token %}
{{ form.as_p }}
<input type = 'submit' value = 'Submit'/>
</form>

ProjectUnite/templates/home.html
  {% extends "base.html" %}
  {% load crispy_forms_tags %}
  {% block content %}
  
  
  <div class="jumbotron">
<section id="main-slider" class="no-margin">
  <div class="carousel slide">
    <ol class="carousel-indicators">
      <li data-target="#main-slider" data-slide-to="0" class="active"></li>
      <li data-target="#main-slider" data-slide-to="1"></li>
      <li data-target="#main-slider" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="item active" style="background-image" img src: "url(images/slider/bg1.jpg)">
        <div class="container">
          <div class="row slide-margin">
            <div class="col-sm-12">
              <div class="carousel-content">
                <h1>Welcome to <span class="logo"><i class="fa fa-bolt"></i> Project Unite</span></h1>
                <h2>Big ideas? Start a project!</h2>
		<h2>Looking to help others out? Search for projects!</h2>
                <a class="btn-slide" href="about-us.html">Read More</a> </div>
            </div>
          </div>
        </div>
      </div>
      <!--/.item-->
      
      <div class="item" style="background-image: url(../../images/slider/bg2.jpg)">
        <div class="container">
          <div class="row slide-margin">
            <div class="col-sm-12">
              <div class="carousel-content">
                <h1>Typi non habent claritatem insitam</h1>
                <h2>Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt laoreet</h2>
                <a class="btn-slide" href="about-us.html">Read More</a> </div>
            </div>
          </div>
        </div>
      </div>
      <!--/.item-->
      
      <div class="item" style="background-image: url(../../images/slider/bg3.jpg)">
        <div class="container">
          <div class="row slide-margin">
            <div class="col-sm-12">
              <div class="carousel-content">
                <h1>Mirum est notare quam littera gothica</h1>
                <h2>Lorem ipsum dolor sit amet, consectetuer adipiscing elit sed diam nonummy nibh euismod tincidunt laoreet</h2>
                <a class="btn-slide" href="about-us.html">Read More</a> </div>
            </div>
          </div>
        </div>
      </div>
      <!--/.item--> 
    </div>
    <!--/.carousel-inner--> 
  </div>
  <!--/.carousel--> 
  <a class="prev hidden-xs" href="#main-slider" data-slide="prev"> <i class="fa fa-chevron-left"></i> </a> <a class="next hidden-xs" href="#main-slider" data-slide="next"> <i class="fa fa-chevron-right"></i> </a> </section>
<!--/#main-slider-->
<div class="color-border"> </div>

<script src="../../js/jquery.js"></script> 
<script src="../../js/bootstrap.min.js"></script> 
<script src="../../js/jquery.prettyPhoto.js"></script> 
<script src="../../js/jquery.isotope.min.js"></script> 
<script src="../../js/main.js"></script>      </div>

{% endblock %}

ProjectUnite/templates/myProjects.html
 {% extends "base.html" %}
 {% load crispy_forms_tags %}
  {% block content %}
  
 <h1>Edit a Project</h1>
 {{ projects.projectID }}
  {% for project in projects %}
  <li><a href = '/editpro/{{ project.projectID }}'>{{ project }}</a> <h6> ProjectID : {{ project.projectID }} </h6></li>

 	</br>

  {% endfor %}

  <p></p>
  <h1>Delete a project</h1>
  <form method='POST' action = '.'>{% csrf_token %}
  {{ form|crispy }}
  {{ title }}
<input class = 'btn btn-primary' type='submit' value = 'DELETE'/>
</form>
  {% endblock %}

ProjectUnite/templates/navbar.html
 <nav class="navbar navbar-inverse" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
        <a class="navbar-brand" href="/"><i class="fa fa-bolt"></i> ProjectUnite</a></a> </div>
      <div class="collapse navbar-collapse navbar-right">
        <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
            <li><a href="/projectlist">Search Projects</a></li>
            <li><a href="/search">Search Users</a></li>
            {% if request.user.is_authenticated %}
            
            <li><a href="/newproject">Create Project</a></li>
            {% else %}


            {% endif %}
     
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
              
        
              <li><a>{{ request.user }}</a></li>
      
              <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            <li><a href="{% url 'registration_register' %}">Register</a></li>
            <li><a href="/projectlist">Search Projects</a></li>
            
	    {% endif %}
          </ul>
      </div>
    </div>
    <!--/.container--> 
  </nav>
  <!--/nav--> 

ProjectUnite/templates/newProject.html
 {% extends "base.html" %}
 {% load crispy_forms_tags %}
  {% block content %}

  <form method='POST' action = '.'>{% csrf_token %}
  	{{ title }}
  {{ form|crispy }}
  
<input class = 'btn btn-primary' type='submit' value = 'SUBMIT'/>
</form>
    {% endblock %}

ProjectUnite/templates/searchProfiles.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<form method='POST' action = '.'>{% csrf_token %}
{{ form|crispy }}
<input type = 'submit' value = 'Submit'/>
</form>


  {% for signup in users %}
 <table border = "1" style = "width:100%">
 	<tr>
 		<td><li><a href = '/members/{{ signup.userID }}'>{{ signup.full_name }}</td></a> <td>Email : {{ signup.email }}</td> <td>Location : {{ signup.location }}</td></br>
 	<td>{{ signup.expertise }}</td></li>
 </tr></br>
 </table>
  {% endfor %}
  {% endblock %}

ProjectUnite/templates/searchProjects.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}


<form method='POST' action = '.'>{% csrf_token %}
{{ form|crispy }}
<input type = 'submit' value = 'Submit'/>
</form>


  {% for project in projects %}
 <table border = "1" style = "width:100%">
 	<tr>
 		<td><li><a href = '/projects/{{ project.projectID }}'>{{ project.name }}</td></a> <td>Email : {{ project.contact_email }}</td> <td>Location : {{ project.location }}</td></br>
 	<td>{{ project.expertise }}</td></li>
 </tr></br>
 </table>
  {% endfor %}
  {% endblock %}

ProjectUnite/templates/single_project.html
 {% extends "base.html" %}
 {% load i18n %}
{% load crispy_forms_tags %}
 {% block content %}
 <h1>information for Project {{ single_project }}</h1>
 <ul>
 <li>Title: {{ single_project.name }}</li>
 <li>Location: {{ single_project.location }}</li>
 <li>Description: {{ single_project.description }}</li>
 <li>Team Members: {{ single_project.team_members }}</li>
 <li>Author: {{ single_project.user }}</li>
 <li>Contact Email: {{ single_project.contact_email }}</li>
</ul>



 {% endblock %}

ProjectUnite/templates/single_user.html
 {% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
 {% block content %}
 <h1>Profile for {{ single_user }}</h1>
 {{ single_user.full_name }}
  {{ single_user.location }}
<div class = 'row'>
<div class = 'col-lg-6'>


<li><img src = '{{ single_user.picture }}' class='img-responsive'/></li>




</div>
  <div class = 'col-lg-6'>
<div class = 'panel'
	<div class = 'panel-heading'> User Information</div>



 <ul>
 	
	<li>Name: {{ single_user.full_name }}</li> 
	<li>Email: {{ single_user.email }}</li>
	<li>CurrentDegree: {{ single_user.CurrentDegree }}</li> 
	<li>location: {{ single_user.location }}</li> 
</ul>
</div>
<div class = 'col-lg-6'>
<div class = 'panel'>
	<div class = 'panel-heading'></div>
<ul>
	
</ul>
</div>
</div>
<div class = 'col-lg-6'>
<div class = 'panel'>
	<div class = 'panel-heading'>Skills and Experience</div>
<ul>
	<li>Skills:</br><p> {{ single_user.skills }}</li></p> 
	<li>Experience:</br><p> {{ single_user.Experience }}</li></p>
	<li>Currentprojects:</br> {{ single_user.Currentprojects }}</li> </p>
</ul>
</div>
</div>
	

	

</ul>
</div>



 {% endblock %}

ProjectUnite/templates/update_profile.html
  {% extends "base.html" %}
  {% load crispy_forms_tags %}

  {% block content %}
  <h1>{{ title }}</h1>
<form method='POST' action = '.'>{% csrf_token %}
	{{ form|crispy }}
	<div class = 'row'>
	
	</div>
<input class = 'btn btn-primary' type='submit' value = 'UPDATE'/>
</form>


  {% endblock %}